### ISSUE TITLE
I found out no skins doesn't work

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#281] opened 2024-04-15 06:12 UTC
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

nothing really to explain the image explains everything

![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/159091869/19a27584-2111-4cd0-9c0f-0d5e96626985)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I only added scripts

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment] 2024-04-15 06:24
is this the latest version/latest action build?

**Comment by daveandbambifan1234** [comment] 2024-04-15 19:35
> is this the latest version/latest action build?

no?

**Comment by JordanSantiagoYT** [comment] 2024-04-20 17:08
Latest commit closes this issue as completed.

**Comment by JordanSantiagoYT** [comment] 2024-04-20 17:09
Also forgot, when making #290 you basically made a duplicate of this issue so lol

**Closed by JordanSantiagoYT** 2024-04-20 17:08 UTC
Labels: bug
