### ISSUE TITLE
Gf Doesnt sing when she hits GF notes

### ISSUE THREAD

**Issue by NonsensicalGH** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#335] opened 2024-05-19 05:17 UTC
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

Jordan wanted me to put this btw

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/165565402/f6722dc6-5682-432d-8b6b-e037dd53209e

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
i dont know why is this happening
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

Yes

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by NonsensicalGH** [comment] 2024-05-19 05:18
The notes were supossed to be GF notes but i didnt shown them here bc of github

**Comment by NonsensicalGH** [comment] 2024-05-19 05:29
Proof

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/165565402/8d3f8e81-e66a-4be7-bd64-0ed9807ea2fc

**Comment by JordanSantiagoYT** [comment] 2024-05-19 05:30
your gf notes are working just fine, are you sure the issue isn't just "gf isn't playing any animations"??

**Comment by NonsensicalGH** [comment] 2024-05-19 05:31
Ah thats what i meant

**Comment by JordanSantiagoYT** [comment] 2024-05-19 05:32
pretty sure thats because your character either doesn't have any animations or the notes you put also have "no animation" turned on, because in the first video i saw gf play one anim

**Comment by JordanSantiagoYT** [comment] 2024-05-19 05:32
https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/3a9b7c2d-9dc2-4a26-820a-8b0e654b1eeb

**Comment by NonsensicalGH** [comment] 2024-05-19 05:35
https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/165565402/e8b63621-2096-45d1-b882-b840b7e7897a

**Comment by NonsensicalGH** [comment] 2024-05-19 05:36
This is the GF character from the issue btw

**Comment by NonsensicalGH** [comment] 2024-05-19 05:42
Gf only sings when the opponent hits a note, and this is what i mean
https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/165565402/1ee72220-2dbe-418e-ac26-d3e174b5b971

**Comment by Joacx21** [comment] 2024-06-08 12:35
> This is the GF character from the issue btw

yeah, i also noticed it when testing the bug

**Comment by JordanSantiagoYT** [comment] 2024-06-11 17:05
BRUH, IM LITERALLY STUPID.

so this only occurs if you have double note ghosts turned on. turn them off and this should be fixed. im working on a full fix rn

**Closed** 2024-06-11 17:25 UTC
Labels: bug
