### ISSUE TITLE
Long Hurt Notes

### ISSUE THREAD

**Issue by Joacx21** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#267] opened 2024-04-06 16:42 UTC
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

If you make a Hold/Long Hurt Note, it looks weird. The image should explain it
![Friday Night Funkin'_ JS Engine - Blammed (Freeplay) 6_04_2024 11_39_32](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/153883016/b173385c-2a58-407c-bb00-fdb226609faa)

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
Just put a Long Hurt Note in the chart
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment] 2024-04-06 17:08
will fix soon

**Comment by JordanSantiagoYT** [comment] 2024-04-06 17:11
that commit was meant to close this as completed, since the issue is fixed on that commit

**Closed by JordanSantiagoYT** 2024-04-06 17:11 UTC
Labels: bug
