### ISSUE TITLE
(A repost) What do i want

### ISSUE THREAD

**Issue by XenonHedgehog** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#342] opened 2024-05-25 08:28 UTC
### What feature do you want to get added on the **base** engine?

BPM Detector (Chart Editor)
I wanna use that option cuz so i can make charts of songs that doesn't have BPM in it/description

Hitbox display (not FNF Android's hitbox buttons)
Do you want to play FNF with hitboxes of hitting notes?

Character-Specific pause music (Animation Editor)
Do you want your bambi to have his pause music?

Mario (mario)
Just
Just mario

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by moxie-coder** [comment] 2024-05-25 08:48
duplicate of #341

**Closed** 2024-05-25 08:48 UTC
Labels: enhancement
