### ISSUE TITLE
Character Editor crash

### ISSUE THREAD

**Issue by radishYT** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#330] opened 2024-05-16 11:33 UTC
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

I was editing the characters animations for about 30 Minutes, and it crashed when I clicked Add/Update.

### Command Prompt/Terminal/Crash logs (if existing)

```bash
flixel/animation/FlxAnimation.hx (Line 239)
flixel/animation/FlxAnimation.hx (Line 206)
flixel/animation/FlxAnimationController.hx (Line 100)
flixel/FlxSprite.hx (Line 766)
flixel/FlxSprite.hx (Line 758)
Character.hx (Line 397)
flixel/group/FlxGroup.hx (Line 151)
flixel/group/FlxGroup.hx (Line 151)
flixel/addons/ui/FlxUIState.hx (Line 212)
MusicBeatState.hx (Line 103)
editors/CharacterEditorState.hx (Line 1447)
flixel/FlxState.hx (Line 239)
flixel/FlxGame.hx (Line 749)
flixel/FlxGame.hx (Line 679)
flixel/FlxGame.hx (Line 558)
openfl/events/EventDispatcher.hx (Line 426)
openfl/display/DisplayObject.hx (Line 1398)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag

> Crash Handler written by: sqirra-rng
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited the window title and the vcr font.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment] 2024-05-16 13:48
duplicate of #325

**Closed by moxie-coder** 2024-05-16 13:48 UTC
Labels: bug
