### ISSUE TITLE
Random error when i hit a note?

### ISSUE THREAD

**Issue by NAEL2XD** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#393] opened 2024-06-16 12:07 UTC
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

![Capture d'écran 2024-06-16 135626](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/108278470/2a00b66a-da79-4f40-8f69-fb5bef14bd40)

basically i hit a note and this pops up, i checked source code and it's rating based so i changed some options and still isn't working? (maybe it's an event but that event didn't crash a single time)

I used commit 4c1fcd4 

### Command Prompt/Terminal/Crash logs (if existing)

```bash
1. Play a song
2. Wait until a note pops up and hit it
3. Crash
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No. 

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment] 2024-06-16 14:30
duplicate of #388

**Closed by moxie-coder** 2024-06-16 14:30 UTC
Labels: bug

**Comment by NAEL2XD** [comment] 2024-06-16 15:54
Oops
