### ISSUE TITLE
Ffmpeg crashing when I try to record chart with 2mil+ notes (I had this problem before)

### ISSUE THREAD

**Issue by dimafut** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#315] opened 2024-05-10 10:48 UTC
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

When I try to record chart with ffmpeg and it's have more than 2 mil notes, FNF lagging and have 5-10 FPS, but if it freeze, ffmpeg crashing without error (my chart have 3,144,528 notes)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment] 2024-05-10 18:55
1. please actually start sending crash logs before i go insane because of how many issues youve made about video evidence. also, i closed the last issue you reported of this because you clearly were using it.
2. this is a duplicate of #297.

**Closed by JordanSantiagoYT** 2024-05-10 18:55 UTC
Labels: bug

**Comment by dimafut** [comment] 2024-05-11 05:45
I have solved this problem then, but now I can't solve it
