### ISSUE TITLE
Y dose not move the title

### ISSUE THREAD

**Issue by daveandbambifan1234** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#185] opened 2024-02-11 06:44 UTC
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

it's just only the Y not the X

this bug has been in JS engine it's whole entire time I wanted to move the logo but the rotate prevents it from putting it to that position can you please fix it
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/159091869/58778f84-e4e3-472d-bea5-0e9861d42527)

### Command Prompt/Terminal logs (if existing)

```bash
o
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
o
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I only added scripts

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here.

Yes

**Comment by StinkTheStinker** [comment] 2024-02-11 07:27
its endY that moves it

titleY = start position of animation
endY = end position of animation

which means that its not a bug

**Comment by StinkTheStinker** [comment] 2024-02-11 07:28
ill give a step by step vid, hold on

**Comment by StinkTheStinker** [comment] 2024-02-11 07:31
https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/34a02d27-b287-4180-87f7-33a4e9cffb51

**Comment by StinkTheStinker** [comment] 2024-02-11 07:31
fullscreen the vid
i forgot to size up the txt

**Comment by daveandbambifan1234** [comment] 2024-02-11 07:32
> fullscreen the vid i forgot to size up the txt

ok good thanks for help

**Comment by StinkTheStinker** [comment] 2024-02-11 07:32
np

**Comment by daveandbambifan1234** [comment] 2024-02-11 07:33
> np

can you join my mod Community, you're actually probably pretty good at doing Sprites and other cool stuff

**Comment by StinkTheStinker** [comment] 2024-02-11 07:46
what is it about exactly?
im tryin to make sure

**Comment by daveandbambifan1234** [comment] 2024-02-11 07:50
well it's for something like code and other stuff

**Comment by StinkTheStinker** [comment] 2024-02-11 07:52
no like, what is the mod about. not the work

**Comment by daveandbambifan1234** [comment] 2024-02-11 08:05
well I would have to explain a lot and that would take too long

**Comment by StinkTheStinker** [comment] 2024-02-11 08:08
i think the logo will explain it

**Comment by StinkTheStinker** [comment] 2024-02-11 08:35
i would close this if i were you

**Comment by StinkTheStinker** [comment] 2024-02-11 08:35
since the thing is solved

**Closed** 2024-02-11 14:11 UTC
Labels: bug
