### ISSUE TITLE
loading problem (possibly only on my side)

### ISSUE THREAD

**Issue by StinkTheStinker** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#310] opened 2024-05-06 16:11 UTC
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

i went ahead and (tried) to update to the 1.24.2 version of the engine, and the songs in the mod folder does not even work
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/145304742/1aa2eafc-c9c1-4f87-ad6d-a24096bf23aa)
i updated from 1.18

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nuh uh

**Comment by JordanSantiagoYT** [comment] 2024-05-06 18:59
you're loading note assets, however the path to your noteskin either doesn't exist, or the xml doesn't exist/is invalid

**Comment by JordanSantiagoYT** [comment] 2024-05-06 19:14
also

1. wrong label, should be labeled as a bug instead
2. based on the line that is crashing the engine, i can tell that this is a duplicate of #240, #192, possibly more issues that report this crash

**Closed by JordanSantiagoYT** 2024-05-06 19:14 UTC
Labels: help wanted

**Comment by StinkTheStinker** [comment] 2024-05-06 22:42
> you're loading note assets, however the path to your noteskin either doesn't exist, or the xml doesn't exist/is invalid

its using the base notes

**Comment by JordanSantiagoYT** [comment] 2024-05-07 00:10
this is line 187
![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/53ef2374-3774-4a6a-8f49-d14998b2c0c2)

are you sure?? like if you changed the noteskin
