### ISSUE TITLE
Screen resolution problem on android.

### ISSUE THREAD

**Issue by Guzqn** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#79] opened 2023-11-17 16:00 UTC
### What is your question?

I have a problem with the screen in JS engine on Android (before of all, YES I HAVE READ THE READ THIS IF YOU HAVE A BUG SO DON'T COMPLAIN) because when I play, the screen looks small! Here is the proof.
![20231117_125739](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/79937435/5cdf0cac-6877-4da6-9396-3c95a84bff9d)
So is there any solution to this problem? (Also I know that jordan Santiago said that the Android version is buggy but I need an answer. Also I tried to change the resolution in the options menu but it gets worse.) 
Device I use: Samsung Galaxy A33 5G

**Comment by JordanSantiagoYT** [comment] 2023-11-17 18:36
Duplicate of #75.

**Closed by JordanSantiagoYT** 2023-11-17 18:36 UTC
Labels: question
