### ISSUE TITLE
apparently I'm not the only one

### ISSUE THREAD

**Issue by averyhungryOpheebopYT** [JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag#221] opened 2024-02-28 18:43 UTC
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

![image](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/89925435/c2e5fb3e-d4ed-4c91-8757-0d0169b4f265)
yeah so uhmm, I dunno what that means, and I did download the latest build, so, I dunno how that works

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

none

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here.

Yes

**Comment by JordanSantiagoYT** [comment] 2024-02-28 20:08
Duplicate of #201, will be fixed when #203 is ready to be merged

**Closed by JordanSantiagoYT** 2024-02-28 20:08 UTC
Labels: bug
